server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      enabled: true

spring:
  mvc:
    pathmatch:
      # swagger setting fail solve. fail cause: default matching-strategy has changed ant-path-matcher -> path_pattern_parser
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    # show-sql: true
    # 테이블이 생성된 이후에 insert 를 실행합니다.
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB

  thymeleaf:
    prefix: classpath:/static/

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  profiles:
    include:
      - cloud
      - mail
      - db

# upload-directory: src/main/resources/upload/

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error