server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    # 테이블이 생성된 이후에 insert 를 실행합니다.
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

upload-directory: src/main/resources/upload