server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      enabled: true


spring:
  mvc:
    pathmatch:
      # swagger setting fail solve. fail cause: default matching-strategy has changed ant-path-matcher -> path_pattern_parser
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

    properties:
      hibernate:
        format_sql: true
    show-sql: true

    # 테이블이 생성된 이후에 insert 를 실행합니다.
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  thymeleaf:
    prefix: classpath:/static/

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  mail:
    default-encoding: UTF-8
    host: smtp.naver.com
    port: 465
    username: tom8672@naver.com
    password: npc2023per4@e
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com

# upload-directory: src/main/resources/upload/

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA45T5MDOASGZFLNUT
      secret-key: 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
    s3:
      bucket: ixconsultingbucket

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error